/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

let fib1 = 1;
let fib2 = 1;
let fibSum = 0

for (let i = 0; fib1 < 4000000 && fib2 < 4000000; i++) {
    fib1 = fib1 + fib2;
    if (fib1 % 2 === 0) {
        fibSum = fibSum + fib1;
    }
    for (let j = 0; j < 1; j++) {
        fib2 = fib2 + fib1;
        if (fib2 % 2 === 0) {
            fibSum = fibSum + fib2;
        }
    }

}

function fibRecursive(n) {
    if (n === 1 || n === 2) {
        return 1;
    }

    return fibRecursive(n - 1) + fibRecursive(n - 2);
}

